compile:
	g++ IntegerArrayQueue.cpp -c -o "IAQ.o" -Wall
	g++ T1.cpp -o "T1.exe" -Wall IAQ.o
	g++ T2.cpp -o "T2.exe" -Wall IAQ.o
	g++ T3.cpp -o "T3.exe" -Wall IAQ.o
	g++ T6.cpp -o "T6.exe" -Wall IAQ.o
	g++ T7.cpp -o "T7.exe" -Wall IAQ.o

run:
	.\T1.exe
	.\T2.exe
	.\T3.exe
	.\T6.exe
	.\T7.exe

clean:
	del *.o
	del *.exe