compile:
	g++ waterJugs.cpp -o waterJugs
	g++ wolfGoatCabbage.cpp -o wolfGoatCabbage

run:
	./waterJugs
	./wolfGoatCabbage

clean:
	del *.exe

water:
	g++ waterJugs.cpp -o waterJugs
	./waterJugs

river:
	g++ wolfGoatCabbage.cpp -o wolfGoatCabbage
	./wolfGoatCabbage