compile:
	g++ T1.cpp -Wall -o "T1.exe"
#g++ T16.cpp -Wall -o "T16.exe"
#g++ T18.cpp -Wall -o "T18.exe"
#g++ T20.cpp -Wall -o "T20.exe"
#g++ T22.cpp -Wall -o "T22.exe"

run:
	.\T1.exe

clean:
	del *.exe