compile:
#g++ T1.cpp -o "T1.exe" -Wall
#g++ T2.cpp -o "T2.exe" -Wall
#g++ T4.cpp -o "T4.exe" -Wall
#g++ T5.cpp -o "T5.exe" -Wall
#g++ T8.cpp -o "T8.exe" -Wall
#g++ T10.cpp -o "T10.exe" -Wall
#g++ T12.cpp -o "T12.exe" -Wall
#g++ T13.cpp -o "T13.exe" -Wall
#g++ T14.cpp -o "T14.exe" -Wall
#g++ T16.cpp -o "T16.exe" -Wall
#g++ T18.cpp -o "T18.exe" -Wall
#g++ T20.cpp -o "T20.exe" -Wall
	g++ T22.cpp -o "T22.exe" -Wall

run:
	.\T22.exe

clean:
	del *.exe