compile:
	g++ review.cpp -c

t1:
	make compile
	g++ T1.cpp review.o -o "T1.exe"
	.\T1.exe
	del T1.exe

t2:
	make compile
	g++ T2.cpp review.o -o "T2.exe"
	.\T2.exe
	del T2.exe

t3:
	make compile
	g++ T3.cpp review.o -o "T3.exe"
	.\T3.exe
	del T3.exe

t4:
	make compile
	g++ T4.cpp review.o -o "T4.exe"
	.\T4.exe
	del T4.exe

t5:
	make compile
	g++ T5.cpp review.o -o "T5.exe"
	.\T5.exe
	del T5.exe

t6:
	make compile
	g++ T6.cpp review.o -o "T6.exe"
	.\T6.exe
	del T6.exe

ts:
	make t1
	make t2
	make t3
	make t4
	make t5
	make t6