compile:
	g++ review.cpp -c -Wall
	g++ T1.cpp review.o -o "T1.exe" -Wall
	g++ T2.cpp review.o -o "T2.exe" -Wall
	g++ T3.cpp review.o -o "T3.exe" -Wall

run:
	.\T1.exe
	.\T2.exe
	.\T3.exe

clean:
	del *.o
	del *.exe