compile:
	g++ "T1.cpp" -Wall -o "T1.exe"
	g++ "T2.cpp" -Wall -o "T2.exe"
	g++ "T3.cpp" -Wall -o "T3.exe"
	g++ "T4.cpp" -Wall -o "T4.exe"
	g++ "T5.cpp" -Wall -o "T5.exe"
	g++ "T6.cpp" -Wall -o "T6.exe"
	g++ "T7.cpp" -Wall -o "T7.exe"
	g++ "T8.cpp" -Wall -o "T8.exe"
	g++ "T9.cpp" -Wall -o "T9.exe"
	g++ "T10.cpp" -Wall -o "T10.exe"
	g++ "T11.cpp" -Wall -o "T11.exe"
	g++ "T12.cpp" -Wall -o "T12.exe"
	g++ "T13.cpp" -Wall -o "T13.exe"
	g++ "T14.cpp" -Wall -o "T14.exe"
	g++ "T15.cpp" -Wall -o "T15.exe"
	g++ "T16.cpp" -Wall -o "T16.exe"
	g++ "T17.cpp" -Wall -o "T17.exe"
	g++ "T18.cpp" -Wall -o "T18.exe"
	g++ "T19.cpp" -Wall -o "T19.exe"
	g++ "T20.cpp" -Wall -o "T20.exe"
	g++ "T21.cpp" -Wall -o "T21.exe"
	g++ "T22.cpp" -Wall -o "T22.exe"
	g++ "T23.cpp" -Wall -o "T23.exe"
	g++ "T24.cpp" -Wall -o "T24.exe"

run:
	.\T1.exe
	.\T2.exe
	.\T3.exe
	.\T4.exe
	.\T5.exe
	.\T6.exe
	.\T7.exe
	.\T8.exe
	.\T9.exe
	.\T10.exe
	.\T11.exe
	.\T12.exe
	.\T13.exe
	.\T14.exe
	.\T15.exe
	.\T16.exe
	.\T17.exe
	.\T18.exe
	.\T19.exe
	.\T20.exe
	.\T21.exe
	.\T22.exe
	.\T23.exe
	.\T24.exe

clean:
	del *.exe

remake:
	g++ makemakefile.cpp -o "remake.exe" -Wall
	.\remake.exe