compile:
	g++ calculatePostfixExpression.cpp -c -o "cPE.o" -Wall
	g++ T1.cpp -o "T1.exe" cPE.o -Wall
	g++ T2.cpp -o "T2.exe" cPE.o -Wall
	g++ T3.cpp -o "T3.exe" cPE.o -Wall
	g++ T4.cpp -o "T4.exe" cPE.o -Wall
	g++ T5.cpp -o "T5.exe" cPE.o -Wall
	g++ T6.cpp -o "T6.exe" cPE.o -Wall
	g++ T9.cpp -o "T9.exe" cPE.o -Wall
	g++ T12.cpp -o "T12.exe" cPE.o -Wall
	g++ T13.cpp -o "T13.exe" cPE.o -Wall
	g++ T14.cpp -o "T14.exe" cPE.o -Wall
	g++ T15.cpp -o "T15.exe" cPE.o -Wall

run:
	.\T1.exe
	.\T2.exe
	.\T3.exe
	.\T4.exe
	.\T5.exe
	.\T6.exe
	.\T9.exe
	.\T12.exe
	.\T13.exe
	.\T14.exe
	.\T15.exe

clean:
	del *.o
	del *.exe