compile:
	g++ Grouping.cpp -Wall -c -o "Grouping.o"
	g++ GroupingMain.cpp -Wall Grouping.o -o "GroupingMain.exe"
	g++ T1.cpp -o "T1.exe" -Wall Grouping.o
	g++ T2.cpp -o "T2.exe" -Wall Grouping.o
	g++ T3.cpp -o "T3.exe" -Wall Grouping.o
	g++ T4.cpp -o "T4.exe" -Wall Grouping.o
	g++ T5.cpp -o "T5.exe" -Wall Grouping.o
	g++ T6.cpp -o "T6.exe" -Wall Grouping.o
	g++ T7.cpp -o "T7.exe" -Wall Grouping.o
	g++ T8.cpp -o "T8.exe" -Wall Grouping.o
	g++ T9.cpp -o "T9.exe" -Wall Grouping.o


run:
	.\GroupingMain.exe
	.\T1.exe
	.\T2.exe
	.\T3.exe
	.\T4.exe
	.\T5.exe
	.\T6.exe
	.\T7.exe
	.\T8.exe
	.\T9.exe

clean:
	del *.o
	del *.exe